[package]
name = "wasm-verifier"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-bls12-381 = "0.4.0"
ark-groth16 = "0.4.0"
ark-relations = "0.4.0"
ark-ff = "0.4.0"
ark-ec = "0.4.0"
rand = "0.8.5"
ark-std = "0.4.0"
